### ISSUE TITLE
Add support for 384 bit ECDSA

### ISSUE THREAD

**Issue by n3cr0cr0w** [vrbyjimmy/EcdsaAcmeNet#2]
I tried to modify and compile this with the default key size changed. All I get after starting the service and trying to get a new cert is 'Unexpected error'.

**Comment by vrbyjimmy** [comment]
Problem was that Let's encrypt registration key is only supported to be 256. I added support for parameter -k KeySize where you can specify keysize for generated certificate. Registration key will still be just 256 bit long, but certificate generated for your site can now have both P-256 and P-384 curves (as I think that P-512 is not supported by LE).

Hope this helps you. You can give it a try with Release v3.0.

I consider this resolved and will close the Issue soon.
